version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - nestjs_network
  nestjs-uploader:
    container_name: nestjs_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    networks:
      - nestjs_network
    depends_on:
      - postgres

networks:
    nestjs_network:
