version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - nestjs_network
  nestjs-uploader:
    container_name: nestjs_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "80:80"
    restart: always
    networks:
      - nestjs_network
    depends_on:
      - postgres

networks:
    nestjs_network:
